// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WifiDirectPacket.proto

package edu.ucla.cs.zyuan.multihopwfd;

public final class PacketProtos {
  private PacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WifiDirectPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:multihopwifidirect.WifiDirectPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
     */
    edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type getType();

    /**
     * <code>required uint32 packetNum = 2;</code>
     */
    boolean hasPacketNum();
    /**
     * <code>required uint32 packetNum = 2;</code>
     */
    int getPacketNum();

    /**
     * <code>required uint64 macAddress = 3;</code>
     */
    boolean hasMacAddress();
    /**
     * <code>required uint64 macAddress = 3;</code>
     */
    long getMacAddress();

    /**
     * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
     */
    boolean hasDestMacAddress();
    /**
     * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
     */
    long getDestMacAddress();

    /**
     * <code>optional bytes content = 5;</code>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 5;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code multihopwifidirect.WifiDirectPacket}
   */
  public static final class WifiDirectPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:multihopwifidirect.WifiDirectPacket)
      WifiDirectPacketOrBuilder {
    // Use WifiDirectPacket.newBuilder() to construct.
    private WifiDirectPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WifiDirectPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WifiDirectPacket defaultInstance;
    public static WifiDirectPacket getDefaultInstance() {
      return defaultInstance;
    }

    public WifiDirectPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WifiDirectPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type value = edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              packetNum_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              macAddress_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              destMacAddress_ = input.readUInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucla.cs.zyuan.multihopwfd.PacketProtos.internal_static_multihopwifidirect_WifiDirectPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucla.cs.zyuan.multihopwfd.PacketProtos.internal_static_multihopwifidirect_WifiDirectPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.class, edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<WifiDirectPacket> PARSER =
        new com.google.protobuf.AbstractParser<WifiDirectPacket>() {
      public WifiDirectPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WifiDirectPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WifiDirectPacket> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code multihopwifidirect.WifiDirectPacket.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST_IP = 0;</code>
       */
      REQUEST_IP(0, 0),
      /**
       * <code>ANSWER_IP = 1;</code>
       */
      ANSWER_IP(1, 1),
      /**
       * <code>DATA = 2;</code>
       */
      DATA(2, 2),
      /**
       * <code>ANONYMITY_KEY = 3;</code>
       */
      ANONYMITY_KEY(3, 3),
      /**
       * <code>ANONYMITY_ENCRYPT = 4;</code>
       */
      ANONYMITY_ENCRYPT(4, 4),
      /**
       * <code>ANONYMITY_REPORT = 5;</code>
       */
      ANONYMITY_REPORT(5, 5),
      /**
       * <code>EXPERIMENTAL_PACKET = 74;</code>
       */
      EXPERIMENTAL_PACKET(6, 74),
      ;

      /**
       * <code>REQUEST_IP = 0;</code>
       */
      public static final int REQUEST_IP_VALUE = 0;
      /**
       * <code>ANSWER_IP = 1;</code>
       */
      public static final int ANSWER_IP_VALUE = 1;
      /**
       * <code>DATA = 2;</code>
       */
      public static final int DATA_VALUE = 2;
      /**
       * <code>ANONYMITY_KEY = 3;</code>
       */
      public static final int ANONYMITY_KEY_VALUE = 3;
      /**
       * <code>ANONYMITY_ENCRYPT = 4;</code>
       */
      public static final int ANONYMITY_ENCRYPT_VALUE = 4;
      /**
       * <code>ANONYMITY_REPORT = 5;</code>
       */
      public static final int ANONYMITY_REPORT_VALUE = 5;
      /**
       * <code>EXPERIMENTAL_PACKET = 74;</code>
       */
      public static final int EXPERIMENTAL_PACKET_VALUE = 74;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return REQUEST_IP;
          case 1: return ANSWER_IP;
          case 2: return DATA;
          case 3: return ANONYMITY_KEY;
          case 4: return ANONYMITY_ENCRYPT;
          case 5: return ANONYMITY_REPORT;
          case 74: return EXPERIMENTAL_PACKET;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:multihopwifidirect.WifiDirectPacket.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type type_;
    /**
     * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
     */
    public edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type getType() {
      return type_;
    }

    public static final int PACKETNUM_FIELD_NUMBER = 2;
    private int packetNum_;
    /**
     * <code>required uint32 packetNum = 2;</code>
     */
    public boolean hasPacketNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 packetNum = 2;</code>
     */
    public int getPacketNum() {
      return packetNum_;
    }

    public static final int MACADDRESS_FIELD_NUMBER = 3;
    private long macAddress_;
    /**
     * <code>required uint64 macAddress = 3;</code>
     */
    public boolean hasMacAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 macAddress = 3;</code>
     */
    public long getMacAddress() {
      return macAddress_;
    }

    public static final int DESTMACADDRESS_FIELD_NUMBER = 4;
    private long destMacAddress_;
    /**
     * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
     */
    public boolean hasDestMacAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
     */
    public long getDestMacAddress() {
      return destMacAddress_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 5;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes content = 5;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      type_ = edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type.REQUEST_IP;
      packetNum_ = 0;
      macAddress_ = 0L;
      destMacAddress_ = 0L;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPacketNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMacAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, packetNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, macAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, destMacAddress_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, packetNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, macAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, destMacAddress_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code multihopwifidirect.WifiDirectPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:multihopwifidirect.WifiDirectPacket)
        edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucla.cs.zyuan.multihopwfd.PacketProtos.internal_static_multihopwifidirect_WifiDirectPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucla.cs.zyuan.multihopwfd.PacketProtos.internal_static_multihopwifidirect_WifiDirectPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.class, edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Builder.class);
      }

      // Construct using edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type.REQUEST_IP;
        bitField0_ = (bitField0_ & ~0x00000001);
        packetNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        macAddress_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        destMacAddress_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucla.cs.zyuan.multihopwfd.PacketProtos.internal_static_multihopwifidirect_WifiDirectPacket_descriptor;
      }

      public edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket getDefaultInstanceForType() {
        return edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.getDefaultInstance();
      }

      public edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket build() {
        edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket buildPartial() {
        edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket result = new edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.packetNum_ = packetNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.macAddress_ = macAddress_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.destMacAddress_ = destMacAddress_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket) {
          return mergeFrom((edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket other) {
        if (other == edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPacketNum()) {
          setPacketNum(other.getPacketNum());
        }
        if (other.hasMacAddress()) {
          setMacAddress(other.getMacAddress());
        }
        if (other.hasDestMacAddress()) {
          setDestMacAddress(other.getDestMacAddress());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasPacketNum()) {
          
          return false;
        }
        if (!hasMacAddress()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type type_ = edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type.REQUEST_IP;
      /**
       * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
       */
      public edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type getType() {
        return type_;
      }
      /**
       * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
       */
      public Builder setType(edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .multihopwifidirect.WifiDirectPacket.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.ucla.cs.zyuan.multihopwfd.PacketProtos.WifiDirectPacket.Type.REQUEST_IP;
        onChanged();
        return this;
      }

      private int packetNum_ ;
      /**
       * <code>required uint32 packetNum = 2;</code>
       */
      public boolean hasPacketNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 packetNum = 2;</code>
       */
      public int getPacketNum() {
        return packetNum_;
      }
      /**
       * <code>required uint32 packetNum = 2;</code>
       */
      public Builder setPacketNum(int value) {
        bitField0_ |= 0x00000002;
        packetNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 packetNum = 2;</code>
       */
      public Builder clearPacketNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packetNum_ = 0;
        onChanged();
        return this;
      }

      private long macAddress_ ;
      /**
       * <code>required uint64 macAddress = 3;</code>
       */
      public boolean hasMacAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 macAddress = 3;</code>
       */
      public long getMacAddress() {
        return macAddress_;
      }
      /**
       * <code>required uint64 macAddress = 3;</code>
       */
      public Builder setMacAddress(long value) {
        bitField0_ |= 0x00000004;
        macAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 macAddress = 3;</code>
       */
      public Builder clearMacAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        macAddress_ = 0L;
        onChanged();
        return this;
      }

      private long destMacAddress_ ;
      /**
       * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
       */
      public boolean hasDestMacAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
       */
      public long getDestMacAddress() {
        return destMacAddress_;
      }
      /**
       * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
       */
      public Builder setDestMacAddress(long value) {
        bitField0_ |= 0x00000008;
        destMacAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 destMacAddress = 4 [default = 0];</code>
       */
      public Builder clearDestMacAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        destMacAddress_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 5;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes content = 5;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 5;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 5;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:multihopwifidirect.WifiDirectPacket)
    }

    static {
      defaultInstance = new WifiDirectPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:multihopwifidirect.WifiDirectPacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_multihopwifidirect_WifiDirectPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_multihopwifidirect_WifiDirectPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026WifiDirectPacket.proto\022\022multihopwifidi" +
      "rect\"\251\002\n\020WifiDirectPacket\0227\n\004type\030\001 \002(\0162" +
      ").multihopwifidirect.WifiDirectPacket.Ty" +
      "pe\022\021\n\tpacketNum\030\002 \002(\r\022\022\n\nmacAddress\030\003 \002(" +
      "\004\022\031\n\016destMacAddress\030\004 \001(\004:\0010\022\017\n\007content\030" +
      "\005 \001(\014\"\210\001\n\004Type\022\016\n\nREQUEST_IP\020\000\022\r\n\tANSWER" +
      "_IP\020\001\022\010\n\004DATA\020\002\022\021\n\rANONYMITY_KEY\020\003\022\025\n\021AN" +
      "ONYMITY_ENCRYPT\020\004\022\024\n\020ANONYMITY_REPORT\020\005\022" +
      "\027\n\023EXPERIMENTAL_PACKET\020JB4\n$edu.ucla.cs." +
      "metro.multihopwifidirectB\014PacketProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_multihopwifidirect_WifiDirectPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_multihopwifidirect_WifiDirectPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_multihopwifidirect_WifiDirectPacket_descriptor,
        new java.lang.String[] { "Type", "PacketNum", "MacAddress", "DestMacAddress", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
